// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermoComfortNew.Data;

#nullable disable

namespace ThermoComfortNew.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420192242_AdminPass")]
    partial class AdminPass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1100)
                        .HasColumnType("nvarchar(1100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Availability = 5,
                            Brand = "Mitsubishi",
                            CategoryId = 1,
                            Characteristics = " Вид Термопомпа: Сплит\r\nЗахранване: 220V\r\nХладилен Агент: R410a\r\nМощност kW: 10 - 12 kW\r\nРаботен режим: Само Отопление\r\nРаботна температура: Нискотемпературна до 65°C",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6061),
                            Description = "Термопомпената система се състои от следните компоненти:\r\n\r\nвъншно тяло\r\nвътрешно тяло Hydrobox\r\nмодул за управление.",
                            ImageUrl = "termopompa1.jpg",
                            Price = 23209.99m,
                            ProductName = "Термопомпа Mitsubishi Electric Power Inverter"
                        },
                        new
                        {
                            ProductId = 2,
                            Availability = 8,
                            Brand = "Daikin ",
                            CategoryId = 1,
                            Characteristics = " Обем в литри: 230 л.\r\nВид Термопомпа: Сплит\r\nЗахранване: 220V\r\nХладилен Агент: R32\r\nМощност kW: 4 - 9 kW\r\nРаботен режим: Отопление и охлаждане\r\nРаботна температура: Нискотемпературна до 65°C",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6074),
                            Description = "Нискотемпературна термопомпа + 230 литров бойлер\r\n› Комбиниран вътрешен модул с вграден неръждаем бойлер 180 или 230 литра и термопомпа за лесен монтаж\r\n› Всички хидравлични компоненти са включени - не са необходими външни компоненти\r\n› Електрическите и хидравлични компоненти са в предната част за лесен достъп\r\n› Компактни размери - отпечатък 595х625 mm\r\n› Вграден помощен нагревател 6 или 9 kW\r\n› Работа в термопомпен режим до -25°C​\r\n› Съвместима с Onecta и гласов контрол​",
                            ImageUrl = "termopompa2.jpg",
                            Price = 15210.12m,
                            ProductName = "Термопомпа Daikin Altherma 3"
                        },
                        new
                        {
                            ProductId = 3,
                            Availability = 15,
                            Brand = "Immergas ",
                            CategoryId = 1,
                            Characteristics = " Вид Термопомпа: Сплит\r\nЗахранване: 380V\r\nХладилен Агент: R410a\r\nМощност kW: 13 - 16 kW\r\nРаботен режим: Отопление и охлаждане\r\nЕнергиен клас отопление: A+++\r\nЕнергиен клас охлаждане: A+",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6082),
                            Description = "ИДЕАЛНА ЗАЩИТА ОТ ЗАМРЪЗВАНЕ Хидравличният модул е напълно защитен от замръзване, поради разположението му вътре в жилището;\r\nКОМПАКТНО РЕШЕНИЕ Обединява в отделния хидравличен модул основните компоненти на хидравличната инсталация, а именно: комплект нагреватели за инсталацията (опция), разширителен съд, 3-пътен превключващ вентил за БГВ, хидравлична група с циркулационна помпа и комплект нагреватели за системата (опция) - до 2 - за версии 12, 14 и 16.\r\nЗАПАЗВАНЕ НА ЕСТЕТИКАТА Външното тяло е по-компактно, което осигурява по-голяма гъвкавост при инсталация на фасадите извън сградата или на тераса.\r\nЛЕСЕН МОНТАЖ Професионалистът може да използва MAGIS PRO V2 като автономно решение за отопление, охлаждане и битова гореща вода или като решениe за интегриране в инсталационни табла и инсталационни табла за вграждане в стена.",
                            ImageUrl = "termopompa3.jpg",
                            Price = 15650.53m,
                            ProductName = "Термопомпа Immergas Magis Pro 14 V2 T"
                        },
                        new
                        {
                            ProductId = 4,
                            Availability = 3,
                            Brand = "Samsung ",
                            CategoryId = 1,
                            Characteristics = " Обем в литри: 260 л.\r\nВид Термопомпа: Сплит с вграден водосъдържател\r\nЗахранване: 380V\r\nХладилен Агент: R32\r\nМощност kW: 13 - 16 kW\r\nРаботен режим: Отопление и охлаждане\r\nРаботна температура: Нискотемпературна до 65°C",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6091),
                            Description = "ClimateHub Mono\r\n– ​Интегрирано решение за отопление и битова гореща вода.\r\n– ​Компактен размер с голям бойлер за битова гореща вода (200 L и 260 L).\r\n– ​Интуитивен, сензорен контролер с цветен екран на няколко езика.\r\n– ​Проследяване на консумираната енергия чрез сензорен контролер.\r\n– ​Безпроблемно обслужване през сервизен прозорец в предната част.\r\n– ​Готовност за включване към фотоволтаици и Smart Grid.\r\n– ​2-зоново управление, подходящо за подово и радиаторно отопление.\r\n– ​Клас на SCOP A+++.\r\n– ​SmartThings система, съвместима с Wi-Fi комплект, предлаган като опция.\r\n– ​За осигуряване на минимална температура на водата е включен резервен нагревател",
                            ImageUrl = "termopompa-4.jpg",
                            Price = 20800.50m,
                            ProductName = "Термопомпа Samsung ClimateHub Mono"
                        },
                        new
                        {
                            ProductId = 5,
                            Availability = 18,
                            Brand = "Toshiba  ",
                            CategoryId = 1,
                            Characteristics = "Вид Термопомпа: Сплит\r\nТип инвертор: Инвертор\r\nЗахранване: 380V\r\nХладилен Агент: R32\r\nМощност kW: 4 - 9 kW\r\nРаботен режим: Отопление и охлаждане\r\nЕнергиен клас отопление: A+++\r\nНиво на шум: 26 - 30dB\r\nWi-Fi: Да\r\nЦвят: Бял",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6099),
                            Description = "Иновативна гама термопомпи. Компактен, ефективен и тих хиромодул. А+++ енергиен клас отопление. Серия ESTIA R32. Опция за свързване с WiFi. Удобни дистанционни управления. Произход Полша.",
                            ImageUrl = "termopompa5.jpg",
                            Price = 9318.98m,
                            ProductName = "Термопомпа Toshiba Estia"
                        },
                        new
                        {
                            ProductId = 6,
                            Availability = 18,
                            Brand = "Immergas ",
                            CategoryId = 2,
                            Characteristics = "Максимална термична мощност\r\n(за БГВ) - 34.9 kW\r\n(за отопление) - 32.7 kW\r\nМинимална термична мощност - 4.0 kW\r\nМаксимална топлинна мощност\r\n(за БГВ) - 34.2 kW\r\n(за отопление) - 32.0 kW\r\nМинимална топлинна мощност - 3.9 kW\r\nЕфективност при:\r\nноминална мощност 80/60°C  -  97.8 %\r\n30% натоварване 80/60°C  -  103.2 %\r\nноминална мощност 40/30°C  -  106.2 %\r\n30% натоварване 40/30°C  -  108.2 %\r\nДебит на газ при горелката (метан) макс./мин. - 3.69 / 0.43 m³/h",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6107),
                            Description = "Повече комфорт със стенния двуконтурен комбиниран кондензен котел VICTRIX. Газовите котли на Immergas отговарят на новите Европейски Директиви за използване на енергия, фокусирани върху кондензната технология. Произведени в Италия. Лесни за инсталация във всяко пространство. Ново поколение котли подходящи за нови и стари вече изградени отоплителни инсталации. Всички модели притежават модулационна циркулационна помпа с нисък разход, за достигане на висока енергийна ефективност. ",
                            ImageUrl = "gazov-kotel1.jpg",
                            Price = 3569.90m,
                            ProductName = "Газов котел Immergas VICTRIX 35 kW TT"
                        },
                        new
                        {
                            ProductId = 7,
                            Availability = 10,
                            Brand = "Immergas",
                            CategoryId = 2,
                            Characteristics = "Термична мощност: Макс. (режим БГВ): 28.7 kW; Макс. (режим отопление): 24.5 kW; Мин.: 4.5 kW",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6116),
                            Description = "Стенен кондензационен котел за отопление и производство на БГВ с външен обемен бойлер. Нов дизайн, ефективност и технология Hydrogen Ready.",
                            ImageUrl = "gazov-kotel2.jpg",
                            Price = 2468.00m,
                            ProductName = "Газов котел Immergas VICTRIX Tera 24 V2 Plus"
                        },
                        new
                        {
                            ProductId = 8,
                            Availability = 8,
                            Brand = "Immergas",
                            CategoryId = 2,
                            Characteristics = "Термична мощност: Макс. (режим БГВ): 34.8 kW; Макс. (режим отопление): 30.5 kW; Мин.: 4.5 kW",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6124),
                            Description = "Стенен кондензационен котел за отопление и производство на БГВ с външен обемен бойлер. Нов дизайн, ефективност и технология Hydrogen Ready.",
                            ImageUrl = "gazov-kotel3.jpg",
                            Price = 3228.00m,
                            ProductName = "Газов котел Immergas VICTRIX Tera 35 V2 Plus"
                        },
                        new
                        {
                            ProductId = 9,
                            Availability = 5,
                            Brand = "Bosch",
                            CategoryId = 2,
                            Characteristics = "Енергиен клас	\r\nA++/A++\r\n\r\nГаранция	\r\nдо 24 месеца\r\n\r\nМаксимална ел. консумация	\r\n94 W\r\n\r\nМощност при 40/30°C-kW	\r\n4,1 - 25,4\r\n\r\nМощност при 50/30°C-kW	\r\n3,3 - 25,2\r\n\r\nМощност при 80/30°C-kW	\r\n3,7 - 24,1\r\n\r\nПроизводител	\r\nBosch",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6132),
                            Description = "Bosch Condens 2500W WBC 28-1 DCE 23 - двуконтурен газов кондензен котел с мощност 3,7-28KW. Работи на принципа на  т. нар. кондензна техника – използва  както топлината, която възниква като измерима температура при процес на горене, така и  топлината от кондензацията на водните пари в отработените газове. ",
                            ImageUrl = "gazov-kotel4.png",
                            Price = 2479.00m,
                            ProductName = "Газов котел Bosch Condens 2500W"
                        },
                        new
                        {
                            ProductId = 10,
                            Availability = 7,
                            Brand = "Viessmann",
                            CategoryId = 2,
                            Characteristics = "Стенен кондензен газов котел Viessmann Vitodens 100-W от 19 до 35 kW, едноконтурен;\r\nКоефициент на ефективност до 98% (Hs)/109% (Hi);\r\nИнтегриран мембранен разширитвисокоефективна работа с пълноценно използване на топлината от конденза;\r\nВентилатор с регулиране на оборотите за тиха и енергоспестяваща работа;\r\nМодулираща цилидрична горелка MatriX;\r\nВисокоефективна помпа;\r\nУправление по константна или по външна температура;\r\nНов осветен LCD-Touch дисплей за лесно и комфортно обслужване;",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6157),
                            Description = "Газов котел Viessmann Vitodens 100-W B1HC301 отговаря напълно на изискванията за енергийна ефективност заложени в Програмата за кредитиране на енергийната ефективност в дома. Vitodens 100-W е високоефективен стенен газов кондензен котел на изключително атрактивна цена и с безкомпромисното качество.",
                            ImageUrl = "gazov-kotel5.jpg",
                            Price = 3369.00m,
                            ProductName = "Газов котел Viessmann Vitodens 100-W "
                        },
                        new
                        {
                            ProductId = 11,
                            Availability = 15,
                            Brand = "Daikin",
                            CategoryId = 4,
                            Characteristics = "Мощност охлаждане: 2.5 kW; Мощност отопление: 2.8 kW; Енергиен клас: A++; Ниво на шум: 21 dB",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6167),
                            Description = "Енергийно ефективен стенен климатик с модерен дизайн и тиха работа. Подходящ за помещения до 25 кв.м.",
                            ImageUrl = "klimatik1.jpg",
                            Price = 1399.00m,
                            ProductName = "Стенен климатик Daikin FTXF25C/RXF25C"
                        },
                        new
                        {
                            ProductId = 12,
                            Availability = 10,
                            Brand = "Mitsubishi Electric",
                            CategoryId = 4,
                            Characteristics = "Мощност охлаждане: 2.5 kW; Мощност отопление: 3.15 kW; Енергиен клас: A+; Ниво на шум: 22 dB",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6175),
                            Description = "Компактен и стилен стенен климатик с висока енергийна ефективност и тих режим на работа.",
                            ImageUrl = "klimatik2.jpeg",
                            Price = 1249.00m,
                            ProductName = "Стенен климатик Mitsubishi Electric MSZ-HR25VF/MUZ-HR25VF"
                        },
                        new
                        {
                            ProductId = 13,
                            Availability = 12,
                            Brand = "Fujitsu",
                            CategoryId = 4,
                            Characteristics = "Мощност охлаждане: 2.5 kW; Мощност отопление: 3.2 kW; Енергиен клас: A++; Ниво на шум: 20 dB",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6183),
                            Description = "Високоефективен стенен климатик с компактен дизайн и ниско ниво на шум. Идеален за малки помещения.",
                            ImageUrl = "klimatik3.webp",
                            Price = 1099.00m,
                            ProductName = "Стенен климатик Fujitsu ASYG09LMCE/AOYG09LMCE"
                        },
                        new
                        {
                            ProductId = 14,
                            Availability = 8,
                            Brand = "Toshiba",
                            CategoryId = 4,
                            Characteristics = "Мощност охлаждане: 2.5 kW; Мощност отопление: 3.2 kW; Енергиен клас: A++; Ниво на шум: 21 dB",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6191),
                            Description = "Елегантен стенен климатик с висока енергийна ефективност и пречистване на въздуха. Подходящ за средни помещения.",
                            ImageUrl = "klimatik4.png",
                            Price = 1299.00m,
                            ProductName = "Стенен климатик Toshiba RAS-B10J2KVG-E/RAS-10J2AVG-E"
                        },
                        new
                        {
                            ProductId = 15,
                            Availability = 20,
                            Brand = "Gree",
                            CategoryId = 4,
                            Characteristics = "Мощност охлаждане: 2.6 kW; Мощност отопление: 2.9 kW; Енергиен клас: A+; Ниво на шум: 22 dB",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6200),
                            Description = "Надежден стенен климатик с инверторна технология и ниско ниво на шум. Идеален за спални и малки офиси.",
                            ImageUrl = "klimatik5.png",
                            Price = 999.00m,
                            ProductName = "Стенен климатик Gree GWH09AAB-K6DNA1A"
                        },
                        new
                        {
                            ProductId = 16,
                            Availability = 5,
                            Brand = "MIA",
                            CategoryId = 3,
                            Characteristics = "Мощност: 15 kW; КПД: 91%; Вместимост на бункера: 20 кг; Консумация на пелети: 1.1 - 3.3 кг/ч; Тегло: 150 кг",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6208),
                            Description = "Автоматична камина на пелети с водна риза, оборудвана с електронна циркулационна помпа, разширителен съд и седмичен програматор.",
                            ImageUrl = "kamina1.jpg",
                            Price = 3430.00m,
                            ProductName = "Камина на пелети MIA IDRO"
                        },
                        new
                        {
                            ProductId = 17,
                            Availability = 8,
                            Brand = "DI CALORE",
                            CategoryId = 3,
                            Characteristics = "Мощност: 18 kW; КПД: 92%; Вместимост на бункера: 25 кг; Консумация на пелети: 1.2 - 3.8 кг/ч; Тегло: 160 кг",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6216),
                            Description = "Камина на пелети с водна риза, произведена с италиански компоненти, осигуряваща висока ефективност и надеждност.",
                            ImageUrl = "kamina2.png",
                            Price = 2904.00m,
                            ProductName = "Камина на пелети DI CALORE"
                        },
                        new
                        {
                            ProductId = 18,
                            Availability = 10,
                            Brand = "BURNIT",
                            CategoryId = 3,
                            Characteristics = "Мощност: 20 kW; КПД: 90%; Вместимост на бункера: 30 кг; Консумация на пелети: 1.5 - 4.5 кг/ч; Тегло: 170 кг",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6224),
                            Description = "Пелетна камина с водна риза, оборудвана с вградена циркулационна помпа, разширителен съд и интелигентно управление.",
                            ImageUrl = "kamina3.jpg",
                            Price = 3369.65m,
                            ProductName = "Камина на пелети BURNIT Advant B2"
                        },
                        new
                        {
                            ProductId = 19,
                            Availability = 7,
                            Brand = "BURNIT",
                            CategoryId = 3,
                            Characteristics = "Мощност: 25 kW; КПД: 91%; Вместимост на бункера: 35 кг; Консумация на пелети: 1.8 - 5.0 кг/ч; Тегло: 180 кг",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6233),
                            Description = "Ефективна камина на пелети с водна риза, подходяща за отопление на средни и големи помещения.",
                            ImageUrl = "kamina4.png",
                            Price = 3369.65m,
                            ProductName = "Камина на пелети BURNIT Advant"
                        },
                        new
                        {
                            ProductId = 20,
                            Availability = 6,
                            Brand = "BURNIT",
                            CategoryId = 3,
                            Characteristics = "Мощност: 22 kW; КПД: 92%; Вместимост на бункера: 28 кг; Консумация на пелети: 1.4 - 4.2 кг/ч; Тегло: 160 кг",
                            CreatedOn = new DateTime(2025, 4, 20, 22, 22, 38, 744, DateTimeKind.Local).AddTicks(6241),
                            Description = "Стилна камина на пелети с водна риза, осигуряваща ефективно отопление и лесно управление.",
                            ImageUrl = "kamina5.png",
                            Price = 3953.90m,
                            ProductName = "Камина на пелети BURNIT Calor"
                        });
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Термопомпи",
                            Description = "Термопомпата е устройство, което използва енергия от външната среда (въздух, вода или земя), за да отоплява или охлажда сгради. "
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Газови котли",
                            Description = "Газовите котли са отоплителни уреди, които използват природен газ или пропан-бутан за затопляне на вода, която циркулира в радиатори, подово отопление или битова гореща вода (БГВ)"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Пелетни камини",
                            Description = "Пелетните камини са отоплителни уреди, които използват дървесни пелети като гориво. Те работят автоматично, като подават пелетите в горивната камера чрез шнек и регулират горенето с вентилатор и електроника."
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Климатици",
                            Description = "Климатикът е уред, който охлажда, отоплява и регулира влажността на въздуха в затворени помещения. Работи чрез топлообменен процес, при който прехвърля топлина от едно място на друго с помощта на хладилен агент (фреон)."
                        });
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.ThermoComfortNew.Domain.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ThermoComfortNew.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ThermoComfortNew.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThermoComfortNew.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ThermoComfortNew.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Order", b =>
                {
                    b.HasOne("ThermoComfortNew.Domain.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("ThermoComfort.Data.Models.Order", "Orders")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThermoComfort.Data.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Product", b =>
                {
                    b.HasOne("ThermoComfortNew.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.ThermoComfortNew.Domain.ShoppingCartItem", b =>
                {
                    b.HasOne("ThermoComfort.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("ThermoComfort.Data.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ThermoComfortNew.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
